<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Cache;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/test-cache', function () {
    // demo cache
    // Cache::put('test_cache_key', 'This is a test cache value.', now()->addMinutes(10));
    // // Sau khoảng thời gian đã định, cache sẽ tự động hết hạn và bị xóa khỏi hệ thống.
    // $check = Cache::has('test_cache_key');

    // return response()->json([
    //     'cache_exists' => $check,
    //     'cache_value' => Cache::get('test_cache_key'),
    // ]);

    // demo remember
    $value = Cache::remember('test_cache_key', now()->addMinutes(10),
        function () {
            return 'This is a test cache value generated by remember.';
        }
    );

    return response()->json([
        'cache_value' => $value,
    ]);
});